trigger: none
pool: Default
steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: sanuazurecloudidwif
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az account show
