trigger: none

pool: 
  name: Default

steps:
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'          # Specifies the cloud provider (AzureRM in this case)
      command: 'custom'           # Using a custom Terraform command
      commandOptions: 'version'   # Running 'terraform version'
      outputTo: 'console'         # Outputting the command's result to the console
